### ISSUE TITLE
Typo in python installation readme

### ISSUE THREAD

**Issue by jxu** [jramseygreen/osu_bot_framework-v3#2]
Current readme says `python3 -m pip -r install requirements.txt` but this gives `-r` flag to pip while it should give to `pip install`, i.e. `python3 -m pip install -r requirements.txt`

**Comment by jxu** [comment]
also my fresh server didn't have pip so maybe mention that: `apt install python3-pip`

**Comment by jramseygreen** [comment]
fixed
