### ISSUE TITLE
Python was not found

### ISSUE THREAD

**Issue by ghost** [jramseygreen/osu_bot_framework-v3#4]
whenever i start launch.exe i get this;
"Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Press any key to continue . . ."

**Comment by jramseygreen** [comment]
Sorry about that, When remaking the exe to fix issue #3 I included the path to python with `/` (the linux path separator) instead of `\` which is the windows path separator. launch.exe has been remade, please redownload.
