### ISSUE TITLE
bot.fetch_user_profile(username) not working

### ISSUE THREAD

**Issue by truonging** [jramseygreen/osu_bot_framework-v3#6]
cant seem to find def fetch_user_profile(username) in the files

**Comment by jramseygreen** [comment]
It is here: https://github.com/jramseygreen/osu_bot_framework-v3/blob/d12004ff43da5169a7e066e85af00c0bc70fdce6/framework.py#L440

**Comment by truonging** [comment]
hey is the function suppose to return an empty dictionary? trying to fetch my profile and its just printing {}

**Comment by jramseygreen** [comment]
Please can you let me know your osu username? I will look into this for you

**Comment by truonging** [comment]
hey sorry it may possibly be i'm using it wrong but it is "truonging" https://osu.ppy.sh/users/21634259

**Comment by jramseygreen** [comment]
osu recently changed the way that the profiles are pushed. I have updated the code, please pull the latest version and al should be good

**Comment by truonging** [comment]
your amazing thankyou!
